apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinterestdemo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinterestdemo
  template:
    metadata:
      labels:
        app: pinterestdemo
    spec:
      containers:
        - name: pinterestdemo
          image: sanjanaa09/sample:pinterestclone
          ports:
            - containerPort: 5000
